"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-06 12:42:51.688448
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=128), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "auth_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.String(length=48), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("passive_score", sa.Float(), nullable=True),
        sa.Column("active_passed", sa.Boolean(), nullable=True),
        sa.Column("frames", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("client_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auth_attempts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_auth_attempts_success"), ["success"], unique=False)
        batch_op.create_index(batch_op.f("ix_auth_attempts_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_auth_attempts_username_created", ["username", "created_at"], unique=False
        )

    op.create_table(
        "face_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("encrypted_embedding", sa.LargeBinary(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("liveness_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("face_templates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_face_templates_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("face_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_face_templates_user_id"))

    op.drop_table("face_templates")
    with op.batch_alter_table("auth_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_auth_attempts_username_created")
        batch_op.drop_index(batch_op.f("ix_auth_attempts_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_attempts_success"))
        batch_op.drop_index(batch_op.f("ix_auth_attempts_created_at"))

    op.drop_table("auth_attempts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    # ### end Alembic commands ###
